name: png_helper
description: A png compress tool for flutter.
version: 1.0.0
repository: https://github.com/omgseven/png_helper

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  png_helper: png_helper

dependencies:
  yaml: ^3.1.1
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
